_BASE_: "Base-HumanLiker.yaml"
MODEL:
  HUMANLIKER:
    USE_DEFORMABLE: True
    PRE_NMS_TOPK_TEST: 2000
    POST_NMS_TOPK_TEST: 1000
  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, False, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
  ROI_HEADS:
    IN_FEATURES: ["p3", "p4"]
SOLVER:
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  CHECKPOINT_PERIOD: 40000
INPUT:
  MIN_SIZE_TRAIN: (480, 960)
  MIN_SIZE_TRAIN_SAMPLING: "range"

DATASETS:
#  TEST: ("coco_2017_val",)
  TEST: ("coco_2017_test-dev",)

DEBUG: False
TEST:
  AUG:
    ENABLED: True
    FLIP: True # single size with only flip
    MIN_SIZES: (400, 600, 800, 1000, 1200, 1400)