_BASE_: "Base-HumanLiker.yaml"
MODEL:
  HUMANLIKER:
    USE_DEFORMABLE: True
    PRE_NMS_TOPK_TEST: 2000
    POST_NMS_TOPK_TEST: 1000
SOLVER:
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  CHECKPOINT_PERIOD: 40000
INPUT:
  MIN_SIZE_TRAIN: (480, 960)
  MIN_SIZE_TRAIN_SAMPLING: "range"



DEBUG: False

DATASETS:
  TEST: ("coco_2017_val",)
#  TEST: ("coco_2017_test-dev",)
#TEST:
#  AUG:
#    ENABLED: True
#    FLIP: True
#    MAX_SIZE: 640
#    MIN_SIZES: (640,)

