_BASE_: "HumanLiker_SwinT_T_1x.yaml"
MODEL:

  WEIGHTS: "pretrain/swin_large_patch4_window12_384_22k_d2.pth"
  SWINT:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    MLP_RATIO: 4
    DROP_PATH_RATE: 0.3

SOLVER:
  IMS_PER_BATCH: 8    # default 16; we don't have enough GPUs for 16 batches
  STEPS: (420000, 500000)  # default (210000, 250000)
  MAX_ITER: 540000   # default (270000)
  CHECKPOINT_PERIOD: 40000
  WEIGHT_DECAY: 0.05
  BASE_LR: 0.00005  # default 0.0001
#  AMP:
#    ENABLED: True

DEBUG: False


#TEST:
#  AUG:
#    ENABLED: True
#    FLIP: True


